import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { Result } from "postcss";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";
import grid from "../public/asset/ico_grid.svg";
import list from "../public/asset/ico_list.svg";
import drink from "../public/asset/drink-img.png";
import keranjang from "../public/asset/keranjang.svg";

//antd
import { CaretRightOutlined } from "@ant-design/icons";
import { Collapse } from "antd";
const { Panel } = Collapse;

// store
import { useSelector } from "react-redux";
import {
  fetchAsyncCategoryDrink,
  fetchAsyncGlassDrink,
  fetchAsyncAlcoholicDrink,
  fetchAsyncDrink,
  fetchAsyncDrinkBycategory,
  fetchAsyncDrinkByGlass,
  fetchAsyncDrinkByAlcoholic,
} from "../features/drinkSlice";
import { useDispatch } from "react-redux";

export default function Home() {
  const [variant, setVariant] = useState("");
  console.log(variant);

  const dispatch = useDispatch();

  const value = useSelector((state) => state.drink.value);
  const drinksList = useSelector((state) => state.drink.drinks);
  const categoryDrink = useSelector((state) => state.drink.category);
  const glassDrink = useSelector((state) => state.drink.glass);
  const alcoholicDrink = useSelector((state) => state.drink.alcoholic);
  console.log(categoryDrink);

  const getDrinkByCategory = (e) => {
    dispatch(fetchAsyncDrinkBycategory(e));
    setVariant(e);
  };

  const getDrinkByGlass = (e) => {
    dispatch(fetchAsyncDrinkByGlass(e));
    setVariant(e);
  };

  const getDrinkByAlcoholic = (e) => {
    dispatch(fetchAsyncDrinkByAlcoholic(e));
    setVariant(e);
  };

  useEffect(() => {
    dispatch(fetchAsyncDrink());
    dispatch(fetchAsyncCategoryDrink());
    dispatch(fetchAsyncGlassDrink());
    dispatch(fetchAsyncAlcoholicDrink());
  }, []);

  return (
    <div className="container w-full h-[100vh] bg-[#16181B] overflow-hidden flex flex-col">
      <div className="px-10">
        <Head>
          <title>Cocktail - Menu</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="py-4 h-28">
          <Navbar />
        </div>
      </div>
      <div className="w-full bg-[#1F2125] flex justify-end gap-4 px-10 py-2 mt-10">
        <Image src={grid} alt="grid" width="24" height="20" />
        <Image src={list} alt="list" width="24" height="20" />
      </div>
      <div className={styles.cardParent}>
        <div className={styles.variant}>
          <h3 className="text-white font-bold text-2xl mb-4">
            Cocktail Variant
          </h3>
          <div>
            <Collapse
              bordered={true}
              expandIcon={({ isActive }) =>
                isActive ? (
                  <CaretRightOutlined
                    rotate={isActive ? 90 : 0}
                    style={{ color: "#FF9100" }}
                  />
                ) : (
                  <CaretRightOutlined />
                )
              }
              className="site-collapse-custom-collapse"
              style={{ backgroundColor: "transparent" }}
            >
              <Panel
                header="Categories"
                key="1"
                className="site-collapse-custom-panel"
                style={{
                  textDecoration: "none",
                  borderBottom: "none",
                  backgroundColor: "#7A7F84",
                }}
              >
                {categoryDrink.map((i) => (
                  <ul>
                    <li
                      className={
                        "pl-6 cursor-pointer " +
                        (variant === i.strCategory ? "text-[#FF9100]" : "")
                      }
                      onClick={(e) => getDrinkByCategory(e.target.innerHTML)}
                    >
                      {i.strCategory}
                    </li>
                  </ul>
                ))}
              </Panel>
            </Collapse>
          </div>
          <div>
            <Collapse
              bordered={true}
              expandIcon={({ isActive }) =>
                isActive ? (
                  <CaretRightOutlined
                    rotate={isActive ? 90 : 0}
                    style={{ color: "#FF9100" }}
                  />
                ) : (
                  <CaretRightOutlined />
                )
              }
              className="site-collapse-custom-collapse"
              style={{ backgroundColor: "transparent" }}
            >
              <Panel
                header="Glass"
                key="1"
                className="site-collapse-custom-panel"
                style={{
                  textDecoration: "none",
                  borderBottom: "none",
                  backgroundColor: "#7A7F84",
                }}
              >
                {glassDrink.map((i) => (
                  <ul>
                    <li
                      className={
                        "pl-6 cursor-pointer " +
                        (variant === i.strGlass ? "text-[#FF9100]" : "")
                      }
                      onClick={(e) => getDrinkByGlass(e.target.innerHTML)}
                    >
                      {i.strGlass}
                    </li>
                  </ul>
                ))}
              </Panel>
            </Collapse>
          </div>
          <div>
            <Collapse
              bordered={true}
              expandIcon={({ isActive }) =>
                isActive ? (
                  <CaretRightOutlined
                    rotate={isActive ? 90 : 0}
                    style={{ color: "#FF9100" }}
                  />
                ) : (
                  <CaretRightOutlined />
                )
              }
              className="site-collapse-custom-collapse"
              style={{ backgroundColor: "transparent" }}
            >
              <Panel
                header="Alcoholic"
                key="1"
                className="site-collapse-custom-panel"
                style={{
                  textDecoration: "none",
                  borderBottom: "none",
                  backgroundColor: "#7A7F84",
                }}
              >
                {alcoholicDrink.map((i) => (
                  <ul>
                    <li
                      className={
                        "pl-6 cursor-pointer " +
                        (variant === i.strAlcoholic ? "text-[#FF9100]" : "")
                      }
                      onClick={(e) => getDrinkByAlcoholic(e.target.innerHTML)}
                    >
                      {i.strAlcoholic}
                    </li>
                  </ul>
                ))}
              </Panel>
            </Collapse>
          </div>
        </div>

        <div className={styles.card}>
          {drinksList.map((i) => (
            <div className="w-[280px] bg-white relative">
              <Image src={drink} alt="list" height="200" width="280" />
              <div className="px-3 pb-8">
                <h4 className="font-bold text-xl mt-2 text-black">
                  {i.strDrink}
                </h4>
                <p className="text-sm text-[#7A7F84] mt-2">
                  Lorem Ipsum is simply dummy text
                </p>
                <div className="flex mt-4">
                  <h5 className="font-semibold text-xl text-black">
                    {value} / WT
                  </h5>
                  <button className="w-28 h-10 bg-[#FF9100] text-white rounded-tl-3xl rounded-bl-3xl font-bold absolute right-0 flex justify-center items-center">
                    Chart{" "}
                    <Image
                      src={keranjang}
                      alt="keranjang"
                      width="20"
                      height="20"
                    />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}
