import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { Result } from "postcss";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const [drinks, setDrinks] = useState({ post: [] });
  const fetchData = async () => {
    try {
      const response = await axios(
        "https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a"
      );
      console.log(response);
      setDrinks({ post: response.data.drinks });
      console.log(drinks, "drinks");
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-2xl font-bold text-center">The Cocktail App</h1>
        <div className="flex gap-3 w-[900px] flex-wrap justify-center">
          {drinks.post.map((i) => (
            <div className="w-[300px] h-[200px] shadow-lg bg-white">
              <h5>{i.strDrink}</h5>
              <Link href={`/detail/${i.idDrink}`}>
                <a>Go Detail!</a>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
